scrape_configs:
  - job_name: 'teste_metricas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5000'] #servidor da aplicação
    scrape_interval: 10s
    scrape_timeout: 5s